name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: tag new versions
      run: |
        version=$(jq .version *.install)
        aliceMinVersion==$(jq .aliceMinVersion *.install)
        git_refs_url=$(jq .repository.git_refs_url ${{ github.event_path }} | tr -d '"' | sed 's/{\/sha}//g')
        echo "tag: $version>=$aliceMinVersion, $git_refs_url"
        curl -s -X POST $git_refs_url \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -d @- << EOF
        {"ref": "refs/tags/$version>=$aliceMinVersion",
        "sha": "${{ github.sha }}"}
        EOF
